SELECT DISTINCT
   sl.SWR_NO,
   swr.SWR_TITLE,
   sl.MT_LOT_ID,
   wis.WAFER_ID,
   s.STEP_NAME
FROM "FAB_{fab}_SWR_DM"."SWR_LOT" sl

INNER JOIN  "FAB_{fab}_SWR_DM"."SWR"  swr
ON sl.SWR_NO = swr.SWR_NO

INNER JOIN "FAB_{fab}_SWR_DM"."SPLIT_DEFINITION" sd
ON sl.SWR_NO = sd.SWR_NO

INNER JOIN "FAB_{fab}_SWR_DM"."SPLIT_GROUP" sg
ON sg.SPLIT_OID = sd.SPLIT_OID

INNER JOIN "FAB_{fab}_SWR_DM"."TRAV_DEF_FOR_GROUP" tdfg
ON sd.SPLIT_OID = tdfg.SPLIT_OID

INNER JOIN "FAB_{fab}_REF_DM"."STEP" s
ON tdfg.SWR_START_STEP_OID = s.STEP_OID

INNER JOIN "FAB_{fab}_SWR_DM"."WAFERS_IN_SPLIT" wis
ON sg.SPLIT_OID = wis.SPLIT_OID AND sg.SPLIT_GROUP_SEQ_NO = wis.SPLIT_GROUP_SEQ_NO

WHERE sl.MT_LOT_ID like ANY ({lot_id}) AND sg.CONTROL_FLAG = 'N'
ORDER BY sl.SWR_NO, sl.MT_LOT_ID, wis.WAFER_ID;